version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: test_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data # Perhatikan format list menggunakan dash (-)

volumes:
  postgres_data: # Definisi volume di level atas
